{"name": "test_get_request_singleusernotfound", "status": "failed", "statusDetails": {"message": "AssertionError: Expected status 404 but got 401\nassert 401 == 404\n +  where 401 = <Response [401]>.status_code", "trace": "self = <test_cases.test_GetRequest.TestGetRequest object at 0x000001FFFC711A60>\n\n    def test_get_request_singleusernotfound(self):\n     log = self.get_the_logs()\n     log.info(\"Starting test_get_request_delayedresponse\")\n    \n     # Send GET request\n     response = requests.get(Get_URL3)\n     log.info(f\"GET response: {response}\")\n    \n     # Validate response\n>    assert response.status_code == 404, f\"Expected status 404 but got {response.status_code}\"\nE    AssertionError: Expected status 404 but got 401\nE    assert 401 == 404\nE     +  where 401 = <Response [401]>.status_code\n\ntest_cases\\test_GetRequest.py:95: AssertionError"}, "attachments": [{"name": "log", "source": "eac15d20-7102-4b7c-814c-bed16221623e-attachment.txt", "type": "text/plain"}], "start": 1747374251758, "stop": 1747374252168, "uuid": "460105b8-5766-4f38-90b4-d7bd2b72bed7", "historyId": "71f5c67e5ce6b42734790dff29c6a116", "testCaseId": "71f5c67e5ce6b42734790dff29c6a116", "fullName": "test_cases.test_GetRequest.TestGetRequest#test_get_request_singleusernotfound", "labels": [{"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_GetRequest"}, {"name": "subSuite", "value": "TestGetRequest"}, {"name": "host", "value": "DESKTOP-FR5AEQ7"}, {"name": "thread", "value": "18428-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_GetRequest"}]}